import json
import logging
from typing import Dict, Any, List, Optional

from chromadb import Collection

logger = logging.getLogger(__name__)


class CaseAgent:
    """
    An agent responsible for retrieving historical soccer precedents and comparing them
    to the current scenario to determine factual relevance.
    """

    N_RESULTS = 1

    def __init__(self, cases_collection: Collection, client: Any, model_name: str = "gpt-4o") -> None:
        """
        Initializes the CaseAgent.

        Args:
            cases_collection: The ChromaDB collection containing historical cases.
            client: The OpenAI client instance for LLM interactions.
            model_name: The LLM model name to use for analysis.
        """
        self.cases_collection = cases_collection
        self.client = client
        self.model_name = model_name

    def search(self, query_text: str) -> Dict[str, Any]:
        """
        Retrieves historical cases based on the query text and analyzes their relevance using an LLM.

        Args:
            query_text: The raw text for text-based questions, or the action description
                        generated by VideoAgent for video-based questions.

        Returns:
            A dictionary containing the relevance judgment, explanation,
            historical verdict, and key differences.
        """
        logger.info("CaseAgent: Searching similar cases for: %s...", query_text[:50])

        top_cases_text = self._rag_retrieve(query_text)
        if top_cases_text is None:
            return {
                "is_relevant": False,
                "similarity_explanation": "Database query failed.",
                "historical_answer": "None",
                "key_difference": "N/A",
            }

        cases_str = "\n".join([f"Historical Case {i + 1}: {c}" for i, c in enumerate(top_cases_text)])
        return self._llm_analyze(query_text, cases_str)

    def _rag_retrieve(self, query_text: str) -> Optional[List[str]]:
        try:
            results = self.cases_collection.query(
                query_texts=[query_text],
                n_results=self.N_RESULTS,
            )

            if results.get("documents") and len(results["documents"]) > 0:
                return results["documents"][0]
            return ["No similar cases found."]

        except Exception as e:
            logger.error("CaseAgent: DB query error: %s", e)
            return None

    def _llm_analyze(self, query_text: str, cases_str: str) -> Dict[str, Any]:
        system_prompt = (
            "You are a specialized Legal Analyst for Soccer Precedents. "
            "Your ONLY job is to determine if a retrieved historical case is FACTUALLY comparable "
            "to the current scenario. "
            "Be extremely skeptical. If the content is different, reject the case."
        )

        user_prompt = (
            f"=== CURRENT SCENARIO ===\n\"{query_text}\"\n\n"
            f"=== RETRIEVED HISTORICAL CASE ===\n\"{cases_str}\"\n\n"
            f"### INSTRUCTIONS ###\n"
            f"1. **Relevance Check**:\n"
            f"   - Does the **physical mechanism** match?\n"
            f"   - Does the **specific topic** match?\n\n"
            f"2. **Output Logic**:\n"
            f"   - If the topics/mechanisms do not match, set 'is_relevant' to False.\n"
            f"   - If they match, extract the answer/verdict.\n\n"
            f"### OUTPUT FORMAT (JSON ONLY) ###\n"
            f"Return a JSON object:\n"
            f"- 'is_relevant': boolean (True only if offense type AND mechanism match substantially)\n"
            f"- 'similarity_explanation': Why it matches or why it fails.\n"
            f"- 'historical_answer': The decision made in the historical case (if mentioned).\n"
            f"- 'key_difference': What makes the current case different?\n"
        )

        try:
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                response_format={"type": "json_object"},
                temperature=0.0,
            )

            if not response.choices:
                logger.warning("CaseAgent: Empty response from API.")
                return {
                    "is_relevant": False,
                    "similarity_explanation": "API returned empty response.",
                    "historical_answer": "Error",
                    "key_difference": "Error",
                }
            raw_content = response.choices[0].message.content
            if not raw_content:
                logger.warning("CaseAgent: Empty content from API.")
                return {
                    "is_relevant": False,
                    "similarity_explanation": "API returned empty content.",
                    "historical_answer": "Error",
                    "key_difference": "Error",
                }
            return json.loads(raw_content)

        except json.JSONDecodeError:
            logger.warning("CaseAgent: LLM returned invalid JSON.")
            return {
                "is_relevant": False,
                "similarity_explanation": "Model failed to generate valid JSON.",
                "historical_answer": "Error",
                "key_difference": "Error",
            }
        except Exception as e:
            logger.error("CaseAgent: LLM call error: %s", e)
            return {
                "is_relevant": False,
                "similarity_explanation": "LLM error occurred.",
                "historical_answer": "Error",
                "key_difference": "Error",
            }
